apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: practise
resources:
  - ../../base
  - ingress.yaml
images:
  - name: ghcr.io/b0tl0f/practise-api
    newName: ghcr.io/b0tl0f/practise-api
    newTag: latest
  - name: ghcr.io/b0tl0f/practise-ui
    newName: ghcr.io/b0tl0f/practise-ui
    newTag: latest
