apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: practise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: ghcr.io/b0tl0f/practise-ui:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 150m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: practise
spec:
  selector:
    app: ui
  ports:
    - port: 80
      targetPort: 80
